### ISSUE TITLE
Create extra job for extracting and validating all needed info from PR

### ISSUE THREAD

**Issue by mgoerens** [openshift-helm-charts/development#296]
At several places in the build.yaml workflow, we extract and validate information from the PR, its files, etc. Typically we need the `category`, `organization`, `chart_name`,  `chart_version` at different times.

There are several occurrences of such redundant calls (e.g. to `get_modified_files`) at different stages of the workflow.

We should create a separate job that takes care of:
1. Extracting all information that is needed by later steps from the PR content.
2. Validate those info (e.g. valid semver version, match between directory structure and info in report.yaml, etc.)
3. Present those info to the other steps

For 3. instead of GitHub outputs, we could populate a file and pass it to the other jobs as a PR artifact (see https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow)

Such a file could look for example like this:

```yaml
pre-check:
    content:
        modified_files:
            - charts/partners/hashicorp/vault/1.13.0/report.yaml
            - ...
        category: partners
        organization: hashicorp # vendor
        version: 1.13.0
        chart_name: vault
        source:
            provided: False
        report:
            provided: True
            signed: False
        owners_file_modified: False
        web_catalog_only: True
    pr_infos:
        api_url:
        PR_number: 30145
```
